apiVersion: v1
kind: ReplicationController
metadata:
  name: server
  labels:
    name: server
spec:
  replicas: 1
  selector:
    name: server
  template:
    metadata:
      labels:
        name: server
    spec:
      containers:
      - name: server
        image: augustbrenner/upbite-server:0.0.2
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
